### ISSUE TITLE
Unable to download the model

### ISSUE THREAD

**Issue by michael-swift** [oxpig/AbLang#2]
Hi there, 

thanks for providing the code and model for use. 

I'm having trouble replicating the example: 

`import ablang

heavy_ablang = ablang.pretrained("heavy")
heavy_ablang.freeze()`

prints "Downloading model ..." 

Which hangs there with no further logging for many hours. 

I find I can navigate via web-browser to the url specified in the code: 
"http://opig.stats.ox.ac.uk/website/data/downloads/" and download the tarball of the model there. 

Best,
Michael

**Comment by TobiasHeOl** [comment]
Hi Michael,

Thanks for your interest in using AbLang. 

Since you are able to download the model directly using the url, I don't think it is something on our side. 

On possible reason the download hangs could be, since the weights of AbLang are downloaded and stored inside the AbLang package, that your environment is in a directory with not enough disk space?

Please let me know if this is the case.

Best,
Tobias

**Comment by michael-swift** [comment]
Thanks Tobias! A possible enhancement would be to add a simple download progress bar. 

In any case for folks who may have the same issue, my workaround was this: 

1. download the model of interest here (heavy in my case)

 http://opig.stats.ox.ac.uk/website/data/downloads/ablang-heavy.tar.gz

2. create a folder called model-weights-heavy in AbLang/ablang/
3. untar the model in that folder
